// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Should be able to login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Should be able to login', async function() {
    await driver.get("https://testingmarathon.com/register/")
    await driver.manage().window().setRect({ width: 974, height: 1068 })
    await driver.findElement(By.id("field-login-login")).sendKeys("lina.puksme@gmail.com")
    await driver.findElement(By.id("field-login-password")).sendKeys("lina.puksme@gmail.com")
    await driver.findElement(By.id("field-login-loginSubmit")).click()
    assert(await driver.findElement(By.linkText("Administration Panel")).getText() == "Administration Panel")
  })
})